set nocompatible              " be iMproved, required
filetype off                  " required

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'VundleVim/Vundle.vim'
Plugin 'ctrlpvim/ctrlp.vim'
Plugin 'tpope/vim-surround'
Plugin 'tpope/vim-repeat'
Plugin 'tpope/vim-commentary'
Plugin 'elixir-editors/vim-elixir'
Plugin 'mhinz/vim-mix-format'
Plugin 'christoomey/vim-tmux-navigator'
Plugin 'christoomey/vim-tmux-runner'
Plugin 'junegunn/fzf.vim'
Plugin 'godlygeek/tabular'
Plugin 'plasticboy/vim-markdown'

call vundle#end()            " required
filetype plugin indent on    " required

syntax on

set number                     
set relativenumber            
set tabstop=2
set shiftwidth=2
set expandtab
set ruler
set scrolloff=4

let mapleader = "\<Space>"
let g:mix_format_on_save = 1
let g:mix_format_silent_errors = 1
let g:vim_markdown_conceal = 2
let g:vim_markdown_conceal_code_blocks = 0
let g:vim_markdown_math = 1
let g:vim_markdown_toml_frontmatter = 1
let g:vim_markdown_frontmatter = 1
let g:vim_markdown_strikethrough = 1
let g:vim_markdown_autowrite = 1
let g:vim_markdown_edit_url_in = 'tab'
let g:vim_markdown_follow_anchor = 1
let g:vim_markdown_folding_disabled = 1
" Make CtrlP use ag for listing the files. Way faster and no useless files.
let g:ctrlp_user_command = 'ag %s -l --hidden --nocolor -g ""'
let g:ctrlp_use_caching = 0

nmap <leader>vr :sp $MYVIMRC<cr>
nmap <leader>so :source $MYVIMRC<cr>
nmap <leader>pi :PluginInstall<cr>
nmap <leader>fs :w<cr>
nmap <leader>v :vnew <C-R>=escape(expand("%:p:h"), ' ') . '/'<cr>
nmap <leader>vi :tabe $MYVIMRC<cr>
nmap <leader>co ggVG*y
nmap 0 ^
nmap j gj
nmap k gk

imap jk <esc>
imap kj <esc>
imap <C-s> <esc>:w<cr>

" zoom a vim pane, <C-w>= to re-balance
nnoremap <leader>- :wincmd _<cr>:wincmd \|<cr>
nnoremap <leader>= :wincmd =<cr>

map <Leader>mt :call VtrSendCommand("mix test")<CR>
map <Leader>mtf :call VtrSendCommand("mix test --failed")<CR>
map <Leader>mtw :call VtrSendCommand("mix test --only wip")<CR>
map <leader>ag :Ag<cr>
map <leader>md :execute "!pandoc " . expand('%t')  "-o ~/output.pdf"<cr> :!open -a Firefox\ Developer\ Edition ~/output.pdf<cr><cr>
map <leader>to :vnew ~/todo.md<cr>

autocmd BufNewFile,BufRead *.md set filetype=markdown
autocmd FileType markdown set cursorline
autocmd FileType markdown setlocal spell spelllang=en_us
autocmd Filetype help nmap <buffer> q :q<cr>
" automatically rebalance windows on vim resize
autocmd VimResized * :wincmd =

command! Q q " Bind :Q to :q
command! Qall qall
command! QA qall
command! E e

set rtp+=/usr/local/opt/fzf
